### ISSUE TITLE
Feature Request: Find unused assets

### ISSUE THREAD

**Issue by yuzushioh** [tsabend/fus#14]
Hi @tsabend 

Awesome tool! very useful🙆🏻‍♂️ Finding unused assets in a project may be a great feature. It would be more useful if this is added 👍  

Thanks!

**Comment by kpavankotesh** [comment]
You can use this tool to find unused assets -> https://github.com/onevcat/FengNiao

**Comment by tsabend** [comment]
Finding unused assets is a useful thing, but out of scope for this project. The tool above looks cool. I'm going to close this issue.
