### ISSUE TITLE
Subclassed classes

### ISSUE THREAD

**Issue by noremac** [tsabend/fus#6]
I have a few classes that are never instantiated directly and only exist to be subclassed. Maybe if a class has any subclasses, it should not be marked as unused?

**Comment by tsabend** [comment]
That is the intended behavior actually, so this is just a bug. I wonder if you could give me a bit more information about this. I have two test cases for this in swift_class_spec.rb lines 79 and 84. Are you using a different amount of spacing than I'm expecting maybe?

**Comment by AlexIzh** [comment]
Hm, I have the same issue. And your test cover this case: 

```
class AxisView: UIView {}
class YAxisView: AxisView {}
class XAxisView: AxisView {}
```

But `fus`  returns me `AxisView` as unused class.

**Comment by tsabend** [comment]
@AlexIzh If you run `fus list` do YAxisView and XAxisView show up?

**Comment by tsabend** [comment]
Another thought: Is it the case that the subclasses in the same file as the superclass and the superclass isn't referenced anywhere else?

**Comment by AlexIzh** [comment]
@tsabend re files: no, all classes have separate file.

**Comment by AlexIzh** [comment]
regarding `fus list`: yes, both files are displayed in the list.
